version: '3.8'

services:
  erp-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://erp_user:erp_password@db:5432/erp_dev
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=debug
      - JWT_SECRET=dev-jwt-secret-not-for-production
      - ERP_ENV=development
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
    working_dir: /app
    command: ["cargo", "run", "--", "--log-level", "debug"]
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=erp_dev
      - POSTGRES_USER=erp_user
      - POSTGRES_PASSWORD=erp_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped

  # Database UI for development
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@erp.dev
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8082:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_dev_data:
  redis_dev_data:
  pgadmin_data:
  cargo_cache:
  target_cache: